//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinoteatr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int PosterID { get; set; }
        public int SeatID { get; set; }
        public Nullable<int> Colum { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> PosterDate { get; set; }
    
        public virtual Poster Poster { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
